version: "3"

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/home/node/api
    ports:
      - 8080:8080
    depends_on: 
      - postgres
    environment: 
      - DB_URI=postgres://root:password@postgres/db
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: sh -c "/wait && ./init.sh"
  
  frontend: 
    container_name: frontend
    build: ./frontend
    expose: 
      - 3000
    ports: 
      - 3000:3000
    volumes:
      - ./frontend:/home/app
      - /node_modules
    links: 
      - backend
    command: yarn start
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true

  postgres:
    container_name: postgres
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=pg
    ports: 
      - 5432:5432
    expose: 
      - 5432
